#!/usr/bin/env python3
"""Regenerate the small index files the site reads to know which per-state files exist.

    data/holders/index.json    states with holders/states/<ST>.json or holders/districts/<ST>.json
    data/economic/index.json   states with economic/states/<ST>.json
    data/crime/index.json      datasets = every data/crime/<name>.json except index.json

Run after adding or removing any of those files. CI fails if the committed indexes are stale.
"""
from slc_data import DATA, dump, load


def states_with(*dirs):
    found = set()
    for d in dirs:
        p = DATA / d
        if p.exists():
            found |= {f.stem for f in p.glob("*.json") if not f.stem.startswith("_")}
    return sorted(found)


def main():
    note = "Lists which per-state files exist. Regenerated by scripts/build_indexes.py."
    dump("holders/index.json", {"version": 1, "note": note, "states": states_with("holders/states", "holders/districts")})
    dump("economic/index.json", {"version": 1, "note": note, "states": states_with("economic/states")})

    crime = load("crime/index.json")
    datasets = []
    for f in sorted((DATA / "crime").glob("*.json")):
        if f.name in ("index.json", "aliases.json"):
            continue
        d = load(f"crime/{f.name}")
        datasets.append({"file": f.name, "year": d.get("year"), "level": d.get("level", "district"),
                         "source": d.get("source", "NCRB")})
    datasets.sort(key=lambda x: (str(x["year"]), x["file"]), reverse=True)
    crime["datasets"] = datasets
    dump("crime/index.json", crime)
    print(f"holders: {len(load('holders/index.json')['states'])} states, "
          f"economic: {len(load('economic/index.json')['states'])} states, crime: {len(datasets)} datasets")


if __name__ == "__main__":
    main()
